name: Destroy VPC and Subnet in GCP

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Deployments

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Authenticate with GCP
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    # Set up gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ica-shared-vpc-host-project

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Plan Terraform destroy
    - name: Terraform Plan Destroy
      run: terraform plan -destroy

    # Destroy Terraform resources
    - name: Terraform Destroy
      run: terraform destroy -auto-approve